# Generated by Django 6.1.2 on 2026-10-07 22:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Tên kho')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã kho')),
                ('location', models.CharField(max_length=255, verbose_name='Địa chỉ kho')),
                ('capacity', models.PositiveIntegerField(default=1000, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Sức chứa tối đa (sản phẩm)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kho bãi',
                'verbose_name_plural': 'Danh sách kho bãi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=60, unique=True, verbose_name='Mã SKU')),
                ('name', models.CharField(max_length=200, verbose_name='Tên sản phẩm')),
                ('category', models.CharField(max_length=100, verbose_name='Danh mục')),
                ('quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Số lượng tồn kho')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Đơn giá')),
                ('status', models.CharField(choices=[('IN_STOCK', 'Còn hàng'), ('LOW_STOCK', 'Sắp hết hàng'), ('OUT_OF_STOCK', 'Hết hàng')], default='OUT_OF_STOCK', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='warehouse.warehouse', verbose_name='Thuộc kho')),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Danh sách sản phẩm',
                'ordering': ['-created_at'],
            },
        ),
    ]
